// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using OnlineСinema.Database;
using OnlineСinema.Models;
using System;
using System.Collections.Generic;

namespace OnlineСinema.Database.Configurations
{
    public partial class EpisodeConfiguration : IEntityTypeConfiguration<Episode>
    {
        public void Configure(EntityTypeBuilder<Episode> entity)
        {
            entity.HasKey(e => e.Id).HasName("episode_pkey");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Seasone).WithMany(p => p.Episodes)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("fkepisode624417");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Episode> entity);
    }
}
