// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using OnlineСinema.Database;
using OnlineСinema.Models;
using System;
using System.Collections.Generic;

namespace OnlineСinema.Database.Configurations
{
    public partial class SeasoneConfiguration : IEntityTypeConfiguration<Seasone>
    {
        public void Configure(EntityTypeBuilder<Seasone> entity)
        {
            entity.HasKey(e => e.Id).HasName("seasone_pkey");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Title).WithMany(p => p.Seasones)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("fkseasone718967");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Seasone> entity);
    }
}
