// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using OnlineСinema.Database;
using OnlineСinema.Models;
using System;
using System.Collections.Generic;

namespace OnlineСinema.Database.Configurations
{
    public partial class TagConfiguration : IEntityTypeConfiguration<Tag>
    {
        public void Configure(EntityTypeBuilder<Tag> entity)
        {
            entity.HasKey(e => e.Id).HasName("tags_pkey");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasMany(d => d.Titles).WithMany(p => p.Tags)
                .UsingEntity<Dictionary<string, object>>(
                    "TagsTitle",
                    r => r.HasOne<Title>().WithMany()
                        .HasForeignKey("Titleid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fktags_title298316"),
                    l => l.HasOne<Tag>().WithMany()
                        .HasForeignKey("Tagsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fktags_title691523"),
                    j =>
                    {
                        j.HasKey("Tagsid", "Titleid").HasName("tags_title_pkey");
                        j.ToTable("tags_title");
                        j.IndexerProperty<Guid>("Tagsid").HasColumnName("tagsid");
                        j.IndexerProperty<Guid>("Titleid").HasColumnName("titleid");
                    });

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Tag> entity);
    }
}
