// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using OnlineСinema.Database;
using OnlineСinema.Models;
using System;
using System.Collections.Generic;

namespace OnlineСinema.Database.Configurations
{
    public partial class UserSeenConfiguration : IEntityTypeConfiguration<UserSeen>
    {
        public void Configure(EntityTypeBuilder<UserSeen> entity)
        {
            entity.HasKey(e => e.Id).HasName("user_seen_pkey");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Episode).WithMany(p => p.UserSeens).HasConstraintName("fkuserseen149973");

            entity.HasOne(d => d.Title).WithMany(p => p.UserSeens).HasConstraintName("fkuserseen355288");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UserSeen> entity);
    }
}
