// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using AdstractHelpers.Storage.Abstraction.Interfases;
using Microsoft.EntityFrameworkCore;

namespace OnlineСinema.Models;

[Table("episode")]
public partial class Episode: IId<Guid>
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }

    [Required]
    [Column("path")]
    public string Path { get; set; }

    [Column("orderindex")]
    public int Orderindex { get; set; }

    [Column("seasoneid")]
    public Guid Seasoneid { get; set; }

    [ForeignKey("Seasoneid")]
    [InverseProperty("Episodes")]
    public virtual Seasone Seasone { get; set; }

    [InverseProperty("Episode")]
    public virtual ICollection<UserSeen> UserSeens { get; set; } = new List<UserSeen>();
}