// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using AdstractHelpers.Storage.Abstraction.Interfases;
using Microsoft.EntityFrameworkCore;

namespace OnlineСinema.Models;

[Table("image")]
public partial class Image: IId<Guid>
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }

    [Required]
    [Column("data")]
    public byte[] Data { get; set; }

    [Required]
    [Column("is_cover")]
    public bool IsCover { get; set; }

    [Required]
    [Column("file_extention")]
    public string fileExtention { get; set; }

    [InverseProperty("Coverimage")]
    public virtual ICollection<Title> TitleCoverimages { get; set; } = new List<Title>();

    [InverseProperty("Tileimage")]
    public virtual ICollection<Title> TitleTileimages { get; set; } = new List<Title>();
}