// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using AdstractHelpers.Storage.Abstraction.Interfases;
using Microsoft.EntityFrameworkCore;

namespace OnlineСinema.Models;

[Table("seasone")]
public partial class Seasone: IId<Guid>
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }

    [Required]
    [Column("path")]
    public string Path { get; set; }

    [Column("orderindex")]
    public int Orderindex { get; set; }

    [Column("titleid")]
    public Guid Titleid { get; set; }

    [InverseProperty("Seasone")]
    public virtual ICollection<Episode> Episodes { get; set; } = new List<Episode>();

    [ForeignKey("Titleid")]
    [InverseProperty("Seasones")]
    public virtual Title Title { get; set; }
}