// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using AdstractHelpers.Storage.Abstraction.Interfases;
using Microsoft.EntityFrameworkCore;

namespace OnlineСinema.Models;

[Table("tags")]
[Index("Name", Name = "tags_name_key", IsUnique = true)]
public partial class Tag : IId<Guid>
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }

    [ForeignKey("Tagsid")]
    [InverseProperty("Tags")]
    public virtual ICollection<Title> Titles { get; set; } = new List<Title>();
}