// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using AdstractHelpers.Storage.Abstraction.Interfases;
using Microsoft.EntityFrameworkCore;

namespace OnlineСinema.Models;

[Table("title")]
[Index("Name", Name = "title_name_key", IsUnique = true)]
public partial class Title: IId<Guid>
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }

    [Required]
    [Column("path")]
    public string Path { get; set; }

    [Column("isfilm")]
    public bool Isfilm { get; set; }

    [Required]
    [Column("description")]
    public string Description { get; set; }

    [Column("coverimageid")]
    public Guid? Coverimageid { get; set; }

    [Column("tileimageid")]
    public Guid? Tileimageid { get; set; }

    [ForeignKey("Coverimageid")]
    [InverseProperty("TitleCoverimages")]
    public virtual Image? Coverimage { get; set; }

    [InverseProperty("Title")]
    public virtual ICollection<Seasone> Seasones { get; set; } = new List<Seasone>();

    [ForeignKey("Tileimageid")]
    [InverseProperty("TitleTileimages")]
    public virtual Image? Tileimage { get; set; }

    [InverseProperty("Title")]
    public virtual ICollection<UserSeen> UserSeens { get; set; } = new List<UserSeen>();

    [ForeignKey("Titleid")]
    [InverseProperty("Titles")]
    public virtual ICollection<Tag> Tags { get; set; } = new List<Tag>();
}