// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace OnlineСinema.Models;

[Table("user_seen")]
public partial class UserSeen
{
    [Key]
    [Column("id")]
    public Guid Id { get; set; }

    [Required]
    [Column("userid")]
    public string Userid { get; set; }

    [Column("titleid")]
    public Guid? Titleid { get; set; }

    [Column("episodeid")]
    public Guid? Episodeid { get; set; }

    [ForeignKey("Episodeid")]
    [InverseProperty("UserSeens")]
    public virtual Episode Episode { get; set; }

    [ForeignKey("Titleid")]
    [InverseProperty("UserSeens")]
    public virtual Title Title { get; set; }

    [ForeignKey("UserId")]
    public virtual IdentityUser User { get; set; }
}